import { ComponentFixture, TestBed } from '@angular/core/testing';
import { Router } from '@angular/router';
import { RouterTestingModule } from '@angular/router/testing';
import { of, throwError } from 'rxjs';
import { vi } from 'vitest';
import { CompanyContextService } from '../../core/context/company-context.service';
import { OperationsWorkflowsService, type RequestModalOptions, type RequestRow, type RequestsPageData, type WorkflowMemberOption } from '../../services/operations-workflows.service';
import { RequestsPageComponent } from './requests';

describe('RequestsPageComponent', () => {
  let fixture: ComponentFixture<RequestsPageComponent>; let component: RequestsPageComponent; let router: Router;
  let workflowsSpy: any;
  const pageData: RequestsPageData = { rows: [], departments: [], members: [], requestTypeOptions: [], statusOptions: [], summary: { total: 0, pending: 0, completed: 0, overdue: 0 } };
  const eligibleMembers: WorkflowMemberOption[] = [{ member_id: 'member-verified', user_id: 'user-verified', label: 'Ahmed Ali', email: 'ahmed@company.com', member_role: 'hr', department_id: 'department-1', department_name: 'Operations', status: 'active', has_open_request: false } as any];
  const modalOptions: RequestModalOptions = { members: eligibleMembers, departments: [] };
  const openRequestRow: RequestRow = { id: 'request-1', status: 'sent', lifecycle_status: 'OPEN_PENDING', request_type: 'scan', requested_at: '2026-07-11T10:00:00.000Z', due_at: null, completed_at: null, cancelled_note: null, target_member_id: 'member-verified', target_member_name: 'Ahmed Ali', target_member_email: 'ahmed@company.com', requested_by_user_id: 'owner-1', requested_by_user_name: 'Owner User', business_profile_id: 'profile-1', business_profile_name: 'Wellar', department_id: 'department-1', department_name: 'Operations', completed_scan_id: null, completed_scan_at: null, notification_count: 0 } as any;
  async function createComponent(navState: Record<string, unknown> | null = null) { vi.mocked(router.getCurrentNavigation).mockReturnValue(navState ? ({ extras: { state: navState } } as never) : null); fixture = TestBed.createComponent(RequestsPageComponent); component = fixture.componentInstance; fixture.detectChanges(); await fixture.whenStable(); fixture.detectChanges(); }
  beforeEach(async () => { workflowsSpy = { getRequestsPageData: vi.fn().mockReturnValue(of(pageData)), getRequestModalOptions: vi.fn().mockReturnValue(of(modalOptions)), createScanRequest: vi.fn().mockReturnValue(of(void 0)) }; await TestBed.configureTestingModule({ imports: [RouterTestingModule.withRoutes([]), RequestsPageComponent], providers: [{ provide: CompanyContextService, useValue: { ensureLoaded: () => of({ context: { activeBusinessProfileId: 'profile-1', activeMemberRole: 'owner' } }), snapshot: () => ({ context: { activeBusinessProfileId: 'profile-1', activeMemberRole: 'owner' } }), getActiveMembership: () => ({ id: 'membership-1', status: 'active', member_role: 'owner' }) } }, { provide: OperationsWorkflowsService, useValue: workflowsSpy }] }).compileComponents(); router = TestBed.inject(Router); vi.spyOn(router, 'getCurrentNavigation').mockReturnValue(null); vi.spyOn(router, 'navigate').mockReturnValue(Promise.resolve(true)); });
  it('opens a real modal and renders the verified target', async () => { await createComponent(); (fixture.nativeElement.querySelector('app-page-header button.dashboard-action-button--primary') as HTMLButtonElement).click(); fixture.detectChanges(); expect(component.showCreateModal).toBe(true); expect(Array.from(fixture.nativeElement.querySelectorAll('option')).map((o: any) => o.textContent?.trim())).toContain('Ahmed Ali - ahmed@company.com - HR'); });
  it('preselects the requested membership id from router state', async () => { await createComponent({ scanRequestTargetMemberId: 'member-verified' }); expect(component.showCreateModal).toBe(true); expect(component.requestForm.memberId).toBe('member-verified'); });
  it('submits the current protected request contract and refreshes the queue', async () => { await createComponent(); component.openCreateModal(); component.requestForm.memberId = 'member-verified'; const initial = workflowsSpy.getRequestsPageData.mock.calls.length; component.submitCreateRequest(); expect(workflowsSpy.createScanRequest).toHaveBeenCalledWith({ target_member_id: 'member-verified', request_type: 'manual' }); expect(workflowsSpy.getRequestsPageData.mock.calls.length).toBe(initial + 1); expect(component.showCreateModal).toBe(false); expect(component.feedback?.text).toBe('Scan request sent successfully.'); });
  it('keeps the modal open when submit fails', async () => { workflowsSpy.createScanRequest.mockReturnValue(throwError(() => new Error('Server rejected the request.'))); await createComponent(); component.openCreateModal(); component.requestForm.memberId = 'member-verified'; component.submitCreateRequest(); expect(component.showCreateModal).toBe(true); expect(component.requestModalError).toBe('Server rejected the request.'); });
  it('labels open requests and blocks duplicate submission', async () => { workflowsSpy.getRequestsPageData.mockReturnValue(of({ ...pageData, rows: [openRequestRow] })); await createComponent(); component.openCreateModal(); expect(component.hasOpenRequestForMember('member-verified')).toBe(true); expect(component.memberOptionLabel(eligibleMembers[0])).toContain(' - Open request'); component.requestForm.memberId = 'member-verified'; component.submitCreateRequest(); expect(workflowsSpy.createScanRequest).not.toHaveBeenCalled(); expect(component.requestModalError).toContain('already has an open scan request'); });
  it('extracts a specific backend conflict message', async () => { await createComponent(); expect((component as any).toServerSafeError({ status: 409, error: { code: 'CONFLICT', message: 'An open scan request already exists for the selected member.' } }, 'Failed')).toBe('An open scan request already exists for the selected member.'); });
  it('shows current no-eligible-recipient guidance', async () => { workflowsSpy.getRequestModalOptions.mockReturnValue(of({ members: [], departments: [] })); await createComponent(); component.openCreateModal(); fixture.detectChanges(); expect(component.showNoEligibleRecipientState).toBe(true); expect(fixture.nativeElement.textContent).toContain('No eligible members are available.'); expect(fixture.nativeElement.textContent).toContain('Invite Member'); });
});
